name: Trigger auto deployment for reverie-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/reverie-api-AutoDeployTrigger-78798c3b-43ef-42b6-afc1-ef1ebcf778f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REVERIEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REVERIEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REVERIEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: reverienlpacr.azurecr.io
          registryUsername: ${{ secrets.REVERIEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REVERIEAPI_REGISTRY_PASSWORD }}
          containerAppName: reverie-api
          resourceGroup: reverie-rg
          imageToBuild: reverienlpacr.azurecr.io/reverie-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


